import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Take a Seat",
  description: "Generated by Luca Gattamelata",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
