import type { Metadata } from "next";
import "./globals.css";
import styles from "./ui/layout.module.css"

export const metadata: Metadata = {
  title: "Take a Seat",
  description: "Generated by Luca Gattamelata",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body className={styles.layout}>
        {children}
      </body>
    </html>
  );
}
