'use client';
import MapComponent from "./components/MapComponent";

export default function Home() {
  return (
    <div>
      <h1>Take a Seat</h1>
      <p>Generated by Luca Gattamelata</p>
      <section>
        <h2>Map</h2>
        <p>Map goes here</p>
        <MapComponent />
      </section>
    </div>
  );
}
